1 sprint done fix
SberKotlinSchool/Sprint-2 pull request #33
Opened 2022-09-11 21:55 UTC by admitriev1992

2022-09-11 21:55 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/83/

2022-09-12 06:26 UTC, Goshiq commented on src/main/kotlin/ProblemA.kt
> +                if (k%2 != 0){
результат выражения k%2 является типом Long, который затем сравнивается с 0 (это тип Int)
чтобы исправить, нужно либо привести k%2 к Int, либо использовать 0 типа Long (определяется записью 0L)
```suggestion
                if (k%2 != 0 L){
```

2022-09-12 06:38 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/84/

2022-09-12 07:11 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/85/

2022-09-12 07:12 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/86/

2022-09-12 07:18 UTC, closed without merging